name: open_street_map_flutter
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

#  open_street_map_flutter_android: ^2.1.10
#  open_street_map_flutter_ios: ^2.1.10
#  open_street_map_flutter_platform_interface: ^2.2.1
  open_street_map_flutter_android:
#    path: '../open_street_map_flutter_android'
    git:
      url: https://github.com/tankste/open_street_map_flutter.git
      ref: main
      path: open_street_map_flutter_android

  open_street_map_flutter_platform_interface:
#    path: '../open_street_map_flutter_platform_interface'
    git:
      url: https://github.com/tankste/open_street_map_flutter.git
      ref: main
      path: open_street_map_flutter_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  plugin_platform_interface: ^2.1.3

flutter:
  plugin:
    platforms:
      android:
        default_package: open_street_map_flutter_android
#      ios:
#        default_package: google_maps_flutter_ios
#  plugin:
#    platforms:
#      android:
#        default_package: google_maps_flutter_android
#      ios:
#        default_package: google_maps_flutter_ios
